version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=
    ports:
      - "3305:3306"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITARY=1
    restart: always
    ports:
      - "8889:80"

  webapp:
    image: webapp
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8081"
    restart: always


    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/webapp?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

